baseURL = "https://sumbar.shankarajayaabadi.co.id/"
languageCode = "id"
title = "Agen & Aplikator Plafon PVC & Wall Panel PVC Sumatera Barat | Desain Modern & Harga Terbaik"
theme = "saeseen-hugo"
summaryLength = 25

[pagination]
  pagerSize = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Spesialis Plafon PVC & Wall Panel PVC di Sumatera Barat - Anti Rayap, Anti Air, Tahan Api. Solusi Interior Modern untuk Rumah, Kantor, dan Bisnis Anda di seluruh wilayah Sumbar."
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/Shankara-logo120x80.png"
  logo_amp = "/images/logo/Shankara-logo512x512.png"
  footer_logo = "/images/logo/Shankara-logo120x80-putih.png"
  favicon = "/images/logo/Shankara-logo512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Duhri"
  telepon = "//+6281279947777"
  whatsapp = "//api.whatsapp.com/send?phone=6281279947777&text=*Halo sumbar.shankarajayaabadi.co.id*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -0.947083
  geo_longitude = 100.417181
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["plafon pvc sumbar", "wall panel pvc sumbar", "plafon anti rayap padang", "plafon tahan api sumatera barat", "wall pvc modern sumbar", "aplikator plafon padang"]
  base_price = 95000
  price_range = 45000
  free_consultation = true
  service_types = [
    "Plafon PVC Modern Anti Rayap",
    "Plafon PVC Tahan Api & Anti Air",
    "Wall Panel PVC Interior",
    "Wall Panel PVC Exterior",
    "Plafon PVC Motif Kayu Eksklusif"
  ]
  categories = ["Plafon PVC Modern", "Wall Panel PVC", "Desain Interior Sumbar"]
  payment_methods = ["Transfer Bank", "Bayar Bertahap", "DP 50%", "Cash on Delivery"]
  cancellation_policies = [
    "Pembatalan dapat dilakukan sebelum pemasangan dimulai.",
    "Pengembalian dana penuh jika hasil pemasangan tidak sesuai kesepakatan.",
    "Revisi gratis untuk pemasangan yang kurang rapi atau tidak sesuai permintaan."
  ]
  area_served = [
    "Padang",
    "Bukittinggi",
    "Payakumbuh",
    "Padang Panjang",
    "Pariaman",
    "Sawahlunto",
    "Solok",
    "Agam",
    "Lima Puluh Kota",
    "Tanah Datar",
    "Pesisir Selatan",
    "Sijunjung",
    "Dharmasraya",
    "Pasaman",
    "Solok Selatan",
    "Padang Pariaman",
    "Pasaman Barat",
    "Kepulauan Mentawai"
  ]
  service_output = "Interior rumah, kantor, dan bisnis tampil modern, elegan, dan nyaman dengan plafon & wall panel PVC berkualitas tinggi di Sumatera Barat."

 # Hero Section
  hero_image = "/images/admin/bg-hero-sumbar.jpg"
  hero_title = "Plafon PVC & Wall Panel PVC Sumatera Barat"
  hero_description = "Upgrade interior Anda di Sumatera Barat dengan Plafon PVC & Wall Panel PVC anti rayap, anti air, dan tahan api. Pilihan motif modern, pemasangan profesional, dan konsultasi gratis untuk setiap kebutuhan desain Anda."
  hero_cta_text = "Lihat Produk & Layanan Kami"
  services_cta_text = "Lihat Produk & Harga"

# Footer Section
  footer_about_title = "Keunggulan Layanan Kami"
  footer_about_description = "Kami menghadirkan plafon & wall panel PVC berkualitas premium untuk seluruh wilayah Sumatera Barat. Material tahan lama, desain kekinian, pemasangan cepat, dan garansi resmi untuk kepuasan Anda."
  footer_services_title = "Alasan Memilih Kami"
  footer_contact_title = "Hubungi Kami"
  footer_bottom_text = "@2025 sumbar.shankarajayaabadi.co.id | Sumatera Barat | All Rights Reserved"

  # Testimonials Section
  testimonials_title = "Testimoni Pelanggan Sumatera Barat"

  [[params.footer_services]]
  text = "sumbar.shankarajayaabadi.co.id menyediakan solusi plafon dan wall panel PVC dengan desain modern, material premium, serta layanan konsultasi dan pemasangan profesional di seluruh Sumatera Barat. Percayakan kebutuhan interior Anda pada tim ahli kami."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jl. Veteran No. 15, Padang, Sumatera Barat"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 812-7994-7777"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "shankarajayaabadi.official1@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Andi|Fauzan|Ilham|Reza|Dimas|Arief|Bagus|Rendy|Yusuf|Fikri}"
  message = "{Pelayanan dari sumbar.shankarajayaabadi.co.id {sangat profesional|ramah|responsif}. Hasil pemasangan plafon PVC di rumah saya {sangat memuaskan|benar-benar rapi|modern sekali}.|Saya {terkesan|sangat puas|senang} dengan kualitas produk dan pemasangan yang {cepat|bersih|tepat waktu}.}"
  response = "{Terima kasih atas {kepercayaan|pilihan} Anda! Kami selalu berusaha memberikan {hasil terbaik|layanan maksimal} untuk pelanggan di Sumatera Barat.|Kami {mengapresiasi|berterima kasih atas} ulasan Anda. Senang bisa membantu mewujudkan interior impian Anda.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Putri|Nadia|Vina|Citra|Mega|Indah|Tia|Rani|Della|Salsa}"
  message = "{Saya memilih sumbar.shankarajayaabadi.co.id karena {banyak pilihan motif|harga bersaing|testimoni bagus}. Hasil pemasangan {sangat rapi|presisi|memuaskan} dan timnya {ramah|profesional|berpengalaman}.|Wall panel PVC yang dipasang {membuat rumah lebih nyaman|menambah estetika ruangan|terlihat lebih modern}. Proses konsultasi juga {mudah|jelas|membantu}.}"
  response = "{Terima kasih atas ulasannya! Kami senang Anda puas dengan {produk|layanan} kami.|Kami {bangga|gembira} dapat membantu Anda menemukan plafon PVC yang {tepat|cocok} untuk rumah Anda di Sumatera Barat.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Adi|Rama|Fajar|Dian|Yoga|Rian|Gilang|Taufik|Bima|Rizal}"
  message = "{Proses pemasangan plafon PVC {sangat cepat|tepat waktu|tanpa kendala} dan hasilnya {sangat bagus|rapi|memuaskan}.|Saya {merekomendasikan|menyarankan} sumbar.shankarajayaabadi.co.id untuk siapa saja yang ingin {plafon berkualitas|interior modern|hasil maksimal} di Sumatera Barat.}"
  response = "{Kami {senang|gembira} dapat memenuhi harapan Anda. Terima kasih atas {kepercayaan|pilihan} Anda!|Terima kasih telah merekomendasikan layanan kami di Sumatera Barat. Kami akan terus {meningkatkan|mempertahankan} kualitas.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Sari|Lestari|Mira|Dewi|Yuni|Aulia|Nisa|Rosa|Dina|Alya}"
  message = "{Plafon PVC dari sumbar.shankarajayaabadi.co.id {membuat ruangan lebih elegan|menambah nilai estetika|tampak mewah}. Tim pemasangan {sangat teliti|profesional|ramah} dan hasilnya {memuaskan|rapi|presisi}.|Saya {sangat puas|terkesan|senang} dengan pelayanan dan kualitas produk yang diberikan.}"
  response = "{Terima kasih atas kepercayaannya! Kami selalu berusaha memberikan {hasil terbaik|layanan maksimal} untuk pelanggan di Sumatera Barat.|Kami {menghargai|berterima kasih atas} ulasan Anda. Senang dapat membantu mewujudkan interior impian Anda.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Bayu|Hendra|Toni|Agung|Dedi|Yanto|Wawan|Rio|Iwan|Galih}"
  message = "{Saya memilih sumbar.shankarajayaabadi.co.id karena {proses konsultasi mudah|harga transparan|tim profesional}. Hasil pemasangan {sangat memuaskan|rapi|tepat waktu} dan kualitas plafonnya {terbaik|premium|tahan lama}.|Plafon PVC yang dipasang {menambah kenyamanan|membuat ruangan lebih modern|sangat sesuai harapan}.}"
  response = "{Terima kasih atas ulasannya! Kami senang dapat membantu proyek Anda.|Kami {mengapresiasi|berterima kasih atas} kepercayaan Anda. Semoga plafon PVC kami selalu memberikan kenyamanan di Sumatera Barat.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Dewi|Nina|Rina|Maya|Lina|Sari|Fitri|Nur|Diah|Ayu}"
  message = "{Pelayanan dari sumbar.shankarajayaabadi.co.id {sangat ramah|profesional|membantu}. Plafon PVC yang dipasang {sangat cocok|ideal|sesuai} dengan desain rumah saya.|Saya {senang|puas|terkesan} dengan hasil pemasangan dan kualitas produk yang diberikan.}"
  response = "{Kami {senang|gembira} mendengar Anda puas dengan layanan kami. Terima kasih atas {kepercayaan|pilihan} Anda!|Terima kasih telah memilih produk kami. Kami akan terus memberikan yang terbaik untuk pelanggan di Sumatera Barat.}"
  rating = 5

[[params.tabelItems]]
  name = "Plafon PVC Modern Anti Rayap"
  price = "380.000 /m²"
[[params.tabelItems]]
  name = "Plafon PVC Tahan Api"
  price = "410.000 /m²"
[[params.tabelItems]]
  name = "Wall Panel PVC Interior"
  price = "400.000 /m²"
[[params.tabelItems]]
  name = "Wall Panel PVC Exterior"
  price = "450.000 /m²"
[[params.tabelItems]]
  name = "Plafon PVC Motif Kayu Eksklusif"
  price = "430.000 /m²"

[params.appliList]
  "Plafon PVC Modern Anti Rayap" = "ruang tamu, ruang keluarga, kamar tidur, aula, ruang serbaguna"
  "Plafon PVC Tahan Api" = "dapur, restoran, area publik, kantor, cafe"
  "Wall Panel PVC Interior" = "dinding ruang tamu, partisi kantor, ruang meeting, ruang belajar"
  "Wall Panel PVC Exterior" = "teras, balkon, fasad bangunan, area outdoor, gazebo"
  "Plafon PVC Motif Kayu Eksklusif" = "villa, resort, hotel, rumah mewah, homestay"

[params.kegunaanList]
  "Plafon PVC Modern Anti Rayap" = "perlindungan optimal dari rayap dan kelembapan, cocok untuk iklim Sumbar"
  "Plafon PVC Tahan Api" = "keamanan ekstra dengan material tahan api, aman untuk dapur dan area publik"
  "Wall Panel PVC Interior" = "menciptakan suasana modern dan elegan di dalam ruangan, mudah dibersihkan"
  "Wall Panel PVC Exterior" = "perlindungan dari cuaca ekstrem dan sinar UV, tahan lama di luar ruangan"
  "Plafon PVC Motif Kayu Eksklusif" = "tampilan natural dan mewah dengan motif kayu premium, cocok untuk properti eksklusif"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Tentang Kami"
    url = "https://shankarajayaabadi.co.id/profile/"
  [[params.menu_items]]
    title = "Harga & Katalog"
    url = "https://shankarajayaabadi.co.id/daftar-harga/"

[params.header]
   title = "Agen & Aplikator Plafon/Wall PVC Sumatera Barat | "
   highlight = "PT. SHANKARA JAYA ABADI"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"
